version: "3.2"
services:
  app-db:
    container_name: app-db
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "eSaude123"
      MYSQL_DATABASE: "openmrs"
      MYSQL_USER: "openmrs"
      MYSQL_PASSWORD: "openmrs"
    ports:
      - "3320:3306"
    command:               
      --max_allowed_packet=404857600
      --innodb-log-file-size=5G
    networks:
      - network
    volumes:
      - datadb:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    restart: unless-stopped # Automatically restart unless stopped manually
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=eSaude123" ]
      interval: 10s
      timeout: 10s
      retries: 5

  app-tomcat:         
    container_name: app-tomcat
    image: tomcat:8-jre8-temurin
    environment:
      JAVA_OPTS: "-Dfile.encoding=UTF-8 -server -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -Xmx8G -Xms8G -XX:MaxPermSize=8G -XX:+UseConcMarkSweepGC -Duser.timezone=Africa/Maputo"
      OPENMRS_RUNTIME_PROPERTIES_FILE: "/usr/local/tomcat/openmrs-runtime.properties"      
    ports:
      - "8080:8080" # Host port 8080 mapped to container port 8080
    networks:
      - network
    depends_on:
      - "app-db"
    volumes:
      - ./mrs/webapps/openmrs.war:/usr/local/tomcat/webapps/openmrs.war
      - ./mrs/OpenMRS:/usr/local/tomcat/.OpenMRS
      - ./mrs/openmrs-runtime.properties:/usr/local/tomcat/openmrs-runtime.properties
    restart: unless-stopped # Automatically restart unless stopped manually
    healthcheck:
      test: "curl -f http://localhost:8080/openmrs || exit 1" # Tomcat-specific healthcheck
      interval: 2s
      timeout: 30s
      retries: 15

networks:
  network:
    driver: bridge

volumes:
  datadb:
  runtime-props: